function system = fcn_make_system(beta, gamma)

S = 89; I = 1; R = 0;
T = S + I + R;
init = fcn_make_table("S", S / T, "I", I / T, "R", R / T);

t0 = 0;
tf = 7 * 14;

system = fcn_make_table( ...
  "init", init, ...
  "t0", t0, ...
  "tf", tf, ...
  "beta", beta, ...
  "gamma", gamma ...
);

end
